import placeholderimg from "../../images/placeholder-image.jpg";
const categoryData = [
    {
      id: 1,
      name: "Electronics",
      products: [
        {
          id: 101,
          name: "Product A1",
          description: "Description for Product A1",
          img: "/images/tablet2.jpg",
          cost: 300,
          cmimiMeZbritje:200,
          company: "Company C" ,
          companyId:3,
          subcategory:"Decoration",
          subcategoryId:1,
          stock: 0,
          Rating:2
        },
        {
          id: 102,
          name: "Product A2",
          description: "Description for Product A2",
          img: "/images/iphone.jpg",
          cost: 250,
          company: "Company A",
          cmimiMeZbritje:200,
          companyId:1,
          subcategory:"Women's Clothing",
          subcategoryId:2,
          stock: 15,
          Rating:3
        },
        {
          id: 103,
          name: "Product A3",
          description: "Description for Product A3",
          img: "/images/tablet2.jpg",
          cost: 400,
          // cmimiMeZbritje:null,
          cmimiMeZbritje:200,
          company: "Company A" ,
          companyId:1,
          subcategory:"Phones",
          subcategoryId:3,
          stock: 10,
          Rating:4
        },
        {
          id: 104,
          name: "Product A4",
          description: "Description for Product A4",
          img: "/images/laptop.webp",
          cost: 350,
          company: "Company A" ,
          cmimiMeZbritje:200,
          companyId:1,
          subcategory:"Decoration",
          subcategoryId:1,
          stock: 25,
          Rating:5
        },
        {
          id: 105,
          name: "Product A5",
          description: "Description for Product A5",
          img: "/images/mac.jpg",
          cost: 200,
          cmimiMeZbritje:null,
          company: "Company D" ,
          companyId:4,
          subcategory:"Women's Clothing",
          subcategoryId:2,
          stock: 18,
          Rating:1
        },
        {
          id: 106,
          name: "Product A6",
          description: "Description for Product A6",
          img: "/images/airpods.webp",
          cost: 150,
          cmimiMeZbritje:null,
          company: "Company A" ,
          companyId:1,
          subcategory:"Laptops",
          subcategoryId:4,
          stock: 22,
        },
        {
          id: 107,
          name: "Product A7",
          description: "Description for Product A7",
          img: "/images/airpods.webp",
          cost: 280,
          cmimiMeZbritje:null,
          company: "Company D" ,
          companyId:4,
          subcategory:"Decoration",
          subcategoryId:1,
          stock: 12,
          Rating:0 // no rating yet
        },
        {
          id: 108,
          name: "Product A8",
          description: "Description for Product A8",
          img:"/images/iphone.jpg",
          cost: 180,
          cmimiMeZbritje:null,
          company: "Company B" ,
          companyId:2,
          subcategory:"Men's Clothing",
          subcategoryId:16,
          stock: 30,
          Rating:2
        },
        {
          id: 109,
          name: "Product A9",
          description: "Description for Product A9",
          img:"/images/iphone.jpg",
          cost: 220,
          cmimiMeZbritje:null,
          company: "Company D" ,
          companyId:4,
          subcategory:"Tablets",
          subcategoryId:5,
          stock: 20,
          Rating:2
        },
        {
          id: 110,
          name: "Product A10",
          description: "Description for Product A10",
          img:  "/images/iphone.jpg",
          cost: 320,
          cmimiMeZbritje:null,
          company: "Company B" ,
          companyId:2,
          subcategory:"Furnitures",
          subcategoryId:6,
          stock: 28,
          Rating:2
        },
      ],
    },
    {
      id: 2,
      name: "Clothes",
      products: [
        {
          id: 201,
          name: "Product B1",
          description: "Description for Product B1",
          img: "/images/placeholder-image.jpg",
          cost: 45.56,
          cmimiMeZbritje:null,
          company: "Company B" ,
          companyId:2,
          subcategory:"Phones",
          subcategoryId:3,
          stock: 50,
          Rating:2
        },
        {
          id: 202,
          name: "Product B2",
          cmimiMeZbritje:null,
          description: "Description for Product B2",
          img: placeholderimg,
          cost: 155,
          company: "Company D" ,
          companyId:4,
          subcategory:"Fantasy",
          subcategoryId:7,
          stock: 40,
          Rating:2
        },
        {
          id: 203,
          name: "Product B3",
          description: "Description for Product B3",
          img: placeholderimg,
          cost: 130.22,
          cmimiMeZbritje:null,
          company: "Company D" ,
          companyId:4,
          subcategory:"Suitcases",
          subcategoryId:8,
          stock: 35,
          Rating:3
        },
        {
          id: 204,
          name: "Product B4",
          description: "Description for Product B4",
          img: placeholderimg,
          cost: 80,
          cmimiMeZbritje:null,
          company: "Company B" ,
          companyId:2,
          subcategory:"Laptops",
          subcategoryId:4,
          stock: 60,
          Rating:5
        },
        {
          id: 205,
          name: "Product B5",
          description: "Description for Product B5",
          img: placeholderimg,
          cost: 120,
          cmimiMeZbritje:null,
          company: "Company B" ,
          companyId:2,
          subcategory:"Romance",
          subcategoryId:9,
          stock: 45,
          Rating:4
        },
        {
          id: 206,
          name: "Product B6",
          description: "Description for Product B6",
          img: placeholderimg,
          cost: 100,
          cmimiMeZbritje:null,
          company: "Company B" ,
          companyId:2,
          subcategory:"Backpacks",
          subcategoryId:10,
          stock: 55,
          Rating:1
        },
        {
          id: 207,
          name: "Product B7",
          description: "Description for Product B7",
          img: placeholderimg,
          cost: 70,
          cmimiMeZbritje:null,
          company: "Company A" ,
          companyId:1,
          subcategory:"Laptops",
          subcategoryId:4,
          stock: 70,
          Rating:5
        },
        {
          id: 208,
          name: "Product B8",
          description: "Description for Product B8",
          img: placeholderimg,
          cost: 95,
          cmimiMeZbritje:null,
          company: "Company B" ,
          subcategory:"Fantasy",
          subcategoryId:7,
          companyId:2,
          stock: 48,
          Rating:3
        },
        {
          id: 209,
          name: "Product B9",
          description: "Description for Product B9",
          img: placeholderimg,
          cost: 110,
          cmimiMeZbritje:null,
          company: "Company B" ,
          companyId:2,
          stock: 38,
          subcategory:"Suitacses",
          subcategoryId:8,
          Rating:4
        },
        {
          id: 210,
          name: "Product B10",
          description: "Description for Product B10",
          img: placeholderimg,
          cost: 150,
          cmimiMeZbritje:null,
          company: "Company B" ,
          companyId:2,
          subcategory:"Phones",
          subcategoryId:3,
          stock: 65,
          Rating:3
        },
      ],
    },
    {
      id: 3,
      name: "Health And Beauty",
      products: [
        {
          id: 301,
          name: "Product C1",
          description: "Description for Product C1",
          img: placeholderimg,
          cost: 123,
          cmimiMeZbritje:null,
          company: "Company B" ,
          companyId:2,
          stock: 25,
          subcategory:"Bracelets",
          subcategoryId:11,
          Rating:1
        },
        {
          id: 302,
          name: "Product C2",
          description: "Description for Product C2",
          img: placeholderimg,
          cost: 55,
          cmimiMeZbritje:null,
          company: "Company B" ,
          companyId:2,
          subcategory:"Fantasy",
          subcategoryId:7,
          stock: 20,
          Rating:3
        },
        {
          id: 303,
          name: "Product C3",
          description: "Description for Product C3",
          img: placeholderimg,
          cost: 130,
          cmimiMeZbritje:null,
          company: "Company A" ,
          companyId:1,
          subcategory:"Skincare",
          subcategoryId:12,
          stock: 15,
          Rating:4
        },
        {
          id: 304,
          name: "Product C4",
          description: "Description for Product C4",
          img: placeholderimg,
          cost: 75,
          cmimiMeZbritje:null,
          company: "Company A" ,
          companyId:1,
          subcategory:"Necklaces",
          subcategoryId:13,
          stock: 30,
          Rating:5
        },
        {
          id: 305,
          name: "Product C5",
          description: "Description for Product C5",
          img: placeholderimg,
          cost: 90,
          cmimiMeZbritje:null,
          company: "Company C" ,
          companyId:3,
          subcategory:"Fantasy",
          subcategoryId:7,
          stock: 22,
          Rating:1
        },
        {
          id: 306,
          name: "Product C6",
          description: "Description for Product C6",
          img: placeholderimg,
          cost: 105,
          cmimiMeZbritje:null,
          company: "Company C" ,
          companyId:3,
          stock: 18,
          subcategory:"Eye Makeup",
          subcategoryId:14,
          Rating:4
        },
        {
          id: 307,
          name: "Product C7",
          description: "Description for Product C7",
          img: placeholderimg,
          cost: 85,
          cmimiMeZbritje:null,
          company: "Company C" ,
          companyId:3,
          stock: 35,
          Rating:3
        },
        {
          id: 308,
          name: "Product C8",
          description: "Description for Product C8",
          img: placeholderimg,
          cost: 120,
          cmimiMeZbritje:null,
          company: "Company C" ,
          companyId:3,
          stock: 28,
          Rating:4
        },
        {
          id: 309,
          name: "Product C9",
          description: "Description for Product C9",
          img: placeholderimg,
          cost: 95,
          cmimiMeZbritje:null,
          company: "Company C" ,
          companyId:3,
          subcategory:"Skincare",
          subcategoryId:12,
          stock: 32,
          Rating:3
        },
        {
          id: 310,
          name: "Product C10",
          description: "Description for Product C10",
          img: placeholderimg,
          cost: 110,
          cmimiMeZbritje:null,
          company: "Company C" ,
          companyId:3,
          subcategory:"Necklaces",
          subcategoryId:13,
          stock: 40,
          Rating:2
        },
      ],
    },
    {
      id: 4,
      name: "Home Utilities",
      products: [
        {
          id: 401,
          name: "Product D1",
          description: "Description for Product D1",
          img: placeholderimg,
          cost: 120,
          cmimiMeZbritje:null,
          company: "Company B" ,
          companyId:2,
          subcategory:"Board Games",
          subcategoryId:15,
          stock: 40,
          Rating:2
        },
        {
          id: 402,
          name: "Product D2",
          description: "Description for Product D2",
          img: placeholderimg,
          cost: 120,
          cmimiMeZbritje:null,
          company: "Company B" ,
          subcategory:"Necklaces",
          subcategoryId:13,
          companyId:2,
          stock: 35,
          Rating:2
        },
        {
          id: 403,
          name: "Product D3",
          description:
            "longeeeeeeeeeeeeeeeeeeeeeeeeeeeeer Description for Product D3 bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
          img: placeholderimg,
          cost: 125,
          cmimiMeZbritje:null,
          company: "Company B" ,
          subcategory:"Laptops",
          subcategoryId:4,
          companyId:2,
          stock: 30,
          Rating:2
        },
        {
          id: 404,
          name: "Product D4",
          description: "Description for Product D4",
          img: placeholderimg,
          cost: 135,
          cmimiMeZbritje:null,
          company: "Company B" ,
          companyId:2,
          subcategory:"Board Games",
          subcategoryId:15,
          stock: 50,
          Rating:2
        },
        {
          id: 405,
          name: "Product D5",
          description: "Description for Product D5",
          img: placeholderimg,
          cost: 95,
          cmimiMeZbritje:null,
          company: "Company B" ,
          companyId:2,
          subcategory:"Rings",
          subcategoryId:16,
          stock: 45,
          Rating:2
        },
        {
          id: 406,
          name: "Product D6",
          description: "Description for Product D6",
          img: placeholderimg,
          cost: 130,
          cmimiMeZbritje:null,
          company: "Company A" ,
          companyId:1,
          subcategory:"Headphones",
          subcategoryId:17,
          stock: 60,
          Rating:2
        },
        {
          id: 407,
          name: "Product D7",
          description: "Description for Product D7",
          img: placeholderimg,
          cost: 110,
          cmimiMeZbritje:null,
          company: "Company B" ,
          subcategory:"Board Games",
          subcategoryId:15,
          companyId:2,
          stock: 55,
          Rating:2
        },
        {
          id: 408,
          name: "Product D8",
          description: "Description for Product D8",
          img: placeholderimg,
          cost: 140,
          cmimiMeZbritje:null,
          company: "Company B" ,
          companyId:2,
          subcategory:"Rings",
          subcategoryId:16,
          stock: 42,
          Rating:2
        },
        {
          id: 409,
          name: "Product D9",
          description: "Description for Product D9",
          img: placeholderimg,
          cost: 115,
          cmimiMeZbritje:null,
          company: "Company A",
          companyId:1,
          subcategory:"Laptops",
          subcategoryId:4,
          stock: 38,
          Rating:2
        },
        {
          id: 410,
          name: "Product D10",
          description: "Description for Product D10",
          img: placeholderimg,
          cost: 150,
          cmimiMeZbritje:null,
          company: "Company A" ,
          subcategory:"Board Games",
          subcategoryId:15,
          companyId:1,
          stock: 48,
          Rating:2
        },
        {
          id: 411,
          name: "Product D11",
          description: "Description for Product D11",
          img: placeholderimg,
          cost: 150,
          cmimiMeZbritje:null,
          company: "Company A" ,
          companyId:1,
          stock: 48,
          Rating:2
        },
      ],
    },
    {
        id: 5,
        name: "Books",
        products: [
          {
            id: 401,
            name: "Product D1",
            description: "Description for Product D1",
            img: placeholderimg,
            cost: 120,
            cmimiMeZbritje:null,
            company: "Company A" ,
            subcategory:"Board Games",
            subcategoryId:15,
            companyId:1,
            stock: 40,
            Rating:2
          },
          {
            id: 402,
            name: "Product D2",
            description: "Description for Product D2",
            img: placeholderimg,
            cost: 120,
            cmimiMeZbritje:null,
            company: "Company B",
            subcategory:"Board Games",
            subcategoryId:15,
            companyId:2,
            stock: 35,
            Rating:2
          },
          {
            id: 403,
            name: "Product D3",
            description:
              "longeeeeeeeeeeeeeeeeeeeeeeeeeeeeer Description for Product D3 bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
            img: placeholderimg,
            cost: 125,
            cmimiMeZbritje:null,
            company: "Company C" ,
            companyId:3,
            subcategory:"Board Games",
            subcategoryId:15,
            stock: 30,
            Rating:4
          },
          {
            id: 404,
            name: "Product D4",
            description: "Description for Product D4",
            img: placeholderimg,
            cost: 135,
            cmimiMeZbritje:null,
            company: "Company A" ,
            subcategory:"Board Games",
            subcategoryId:15,
            companyId:1,
            stock: 50,
            Rating:3
          },
          {
            id: 405,
            name: "Product D5",
            description: "Description for Product D5",
            img: placeholderimg,
            cost: 95,
            cmimiMeZbritje:null,
            company: "Company C" ,
            companyId:3,
            subcategory:"Board Games",
            subcategoryId:15,
            stock: 45,
            Rating:2
          },
          {
            id: 406,
            name: "Product D6",
            description: "Description for Product D6",
            img: placeholderimg,
            cost: 130,
            cmimiMeZbritje:null,
            company: "Company D" ,
            companyId:4,
            subcategory:"Board Games",
            subcategoryId:15,
            stock: 60,
            Rating:4
          },
          {
            id: 407,
            name: "Product D7",
            description: "Description for Product D7",
            img: placeholderimg,
            cost: 110,
            cmimiMeZbritje:null,
            company: "Company A" ,
            companyId:1,
            subcategory:"Board Games",
            subcategoryId:15,
            stock: 55,
            Rating:3

          },
          {
            id: 408,
            name: "Product D8",
            description: "Description for Product D8",
            img: placeholderimg,
            cost: 140,
            cmimiMeZbritje:null,
            company: "Company A" ,
            companyId:1,
            subcategory:"Board Games",
            subcategoryId:15,
            stock: 42,
            Rating:2
          },
          {
            id: 409,
            name: "Product D9",
            description: "Description for Product D9",
            img: placeholderimg,
            cost: 115,
            cmimiMeZbritje:null,
            company: "Company A" ,
            companyId:1,
            stock: 38,
            subcategory:"Board Games",
            subcategoryId:15,
            Rating:4
          },
          {
            id: 410,
            name: "Product D10",
            description: "Description for Product D10",
            img: placeholderimg,
            cost: 150,
            cmimiMeZbritje:null,
            company: "Company A" ,
            companyId:1,
            subcategory:"Board Games",
            subcategoryId:15,
            stock: 48,
            Rating:3
          },
          {
            id: 411,
            name: "Product D11",
            description: "Description for Product D11",
            img: placeholderimg,
            cost: 150,
            cmimiMeZbritje:null,
            company: "Company D" ,
            subcategory:"Board Games",
            subcategoryId:15,
            companyId:4,
            stock: 48,
            Rating:2
          },
        ],
      },
      {
        id: 6,
        name: "Accessories",
        products: [
          {
            id: 412,
            name: "Product D1",
            description: "Description for Product D1",
            img: placeholderimg,
            cost: 120,
            cmimiMeZbritje:null,
            company: "Company A" ,
            companyId:1,
            subcategory:"Board Games",
            subcategoryId:15,
            stock: 40,
            Rating:2
          },
          {
            id: 413,
            name: "Product D2",
            description: "Description for Product D2",
            img: placeholderimg,
            cost: 120,
            cmimiMeZbritje:null,
            company: "Company B",
            subcategory:"Board Games",
            subcategoryId:15,
            companyId:2,
            stock: 35,
            Rating:2
          },
          {
            id: 414,
            name: "Product D3",
            description:
              "longeeeeeeeeeeeeeeeeeeeeeeeeeeeeer Description for Product D3 bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
            img: placeholderimg,
            cost: 415,
            cmimiMeZbritje:null,
            company: "Company C" ,
            companyId:3,
            subcategory:"Board Games",
            subcategoryId:15,
            stock: 30,
            Rating:2
          },
          {
            id: 415,
            name: "Product D4",
            description: "Description for Product D4",
            img: placeholderimg,
            cost: 135,
            cmimiMeZbritje:null,
            company: "Company A" ,
            companyId:1,
            subcategory:"Board Games",
            subcategoryId:15,
            stock: 50,
            Rating:2
          },
          {
            id: 417,
            name: "Product D5",
            description: "Description for Product D5",
            img: placeholderimg,
            cost: 95,
            cmimiMeZbritje:null,
            company: "Company C" ,
            companyId:3,
            subcategory:"Board Games",
            subcategoryId:15,
            stock: 45,
            Rating:2
          },
          {
            id: 418,
            name: "Product D6",
            description: "Description for Product D6",
            img: placeholderimg,
            cost: 130,
            cmimiMeZbritje:null,
            company: "Company D" ,
            companyId:4,
            subcategory:"Board Games",
            subcategoryId:15,
            stock: 60,
            Rating:2
          },
          {
            id: 419,
            name: "Product D7",
            description: "Description for Product D7",
            img: placeholderimg,
            cost: 110,
            cmimiMeZbritje:null,
            company: "Company A" ,
            companyId:1,
            subcategory:"Board Games",
            subcategoryId:15,
            stock: 55,
            Rating:2
          },
          {
            id: 420,
            name: "Product D8",
            description: "Description for Product D8",
            img: placeholderimg,
            cost: 140,
            cmimiMeZbritje:null,
            company: "Company A" ,
            companyId:1,
            subcategory:"Board Games",
            subcategoryId:15,
            stock: 42,
            Rating:2
          },
          {
            id: 421,
            name: "Product D9",
            description: "Description for Product D9",
            img: placeholderimg,
            cost: 115,
            cmimiMeZbritje:null,
            company: "Company A" ,
            companyId:1,
            subcategory:"Board Games",
            subcategoryId:15,
            stock: 38,
            Rating:2
          },
          {
            id: 422,
            name: "Product D10",
            description: "Description for Product D10",
            img: placeholderimg,
            cost: 150,
            cmimiMeZbritje:null,
            company: "Company A" ,
            companyId:1,
            stock: 48,
            subcategory:"Board Games",
            subcategoryId:15,
            Rating:2
          },
          {
            id: 423,
            name: "Product D11",
            description: "Description for Product D11",
            img: placeholderimg,
            cost: 150,
            cmimiMeZbritje:null,
            company: "Company D" ,
            subcategory:"Board Games",
            subcategoryId:15,
            companyId:4,
            stock: 48,
            Rating:3
          },
        ],
      }
  ];

  export default categoryData;