import placeholderimg from "../../images/placeholder-image.jpg";

const companyCategoryData = [
  {
    id: 1,
    name: "Company A",
    categoryId: 4,
    categoryName: "Home Utilities",
    products: [
      {
        id: 101,
        name: "Product A1",
        description: "Description for Product A1",
        img: "/images/shoe.jpeg",
        cost: 300,
        subcategory: "Decoration",
        subcategoryId: 1,
        stock: 20,
        Rating: 2,
      },
      {
        id: 104,
        name: "Product A4",
        description: "Description for Product A4",
        img: "/images/laptop.webp",
        cost: 350,
        subcategory: "Decoration",
        subcategoryId: 1,
        stock: 25,
        Rating: 2,
      },
      {
        id: 107,
        name: "Product A7",
        description: "Description for Product A7",
        img: "/images/laptopBag.jpg",
        cost: 280,
        subcategory: "Decoration",
        subcategoryId: 1,
        stock: 12,
        Rating: 2,
      },
      {
        id: 110,
        name: "Product A10",
        description: "Description for Product A10",
        img: "/images/laptopBag.jpg",
        cost: 320,
        subcategory: "Furnitures",
        subcategoryId: 6,
        stock: 28,
        Rating: 2,
      },
    ],
  },
  {
    id: 1,
    name: "Company A",
    categoryId: 2,
    categoryName: "Clothes",
    products: [
      {
        id: 102,
        name: "Product A2",
        description: "Description for Product A2",
        img: "/images/iphone.jpg",
        cost: 250,
        subcategory: "Women's Clothing",
        subcategoryId: 2,
        stock: 15,
        Rating: 2,
      },
      {
        id: 105,
        name: "Product A5",
        description: "Description for Product A5",
        img: "/images/mac.jpg",
        cost: 200,
        subcategory: "Women's Clothing",
        subcategoryId: 2,
        stock: 18,
        Rating: 2,
      },
      {
        id: 108,
        name: "Product A8",
        description: "Description for Product A8",
        img: "/images/cardigan.jpeg",
        cost: 180,
        subcategory: "Men's Clothing",
        subcategoryId: 16,
        stock: 30,
        Rating: 2,
      },
    ],
  },
  {
    id: 1,
    name: "Company A",
    categoryId: 1,
    categoryName: "Electronics",
    products: [
      {
        id: 103,
        name: "Product A3",
        description: "Description for Product A3",
        img: "/images/shoe.jpeg",
        cost: 400,
        subcategory: "Phones",
        subcategoryId: 3,
        stock: 10,
        Rating: 2,
      },
      {
        id: 106,
        name: "Product A6",
        description: "Description for Product A6",
        img: "/images/airpods.webp",
        cost: 150,
        subcategory: "Laptops",
        subcategoryId: 4,
        stock: 22,
        Rating: 2,
      },
      {
        id: 109,
        name: "Product A9",
        description: "Description for Product A9",
        img: placeholderimg,
        cost: 220,
        subcategory: "Tablets",
        subcategoryId: 5,
        stock: 20,
        Rating: 2,
      },
    ],
  },
  {
    id: 2,
    name: "Company B",
    categoryName: "Books",
    categoryId: 5,
    products: [
      {
        id: 202,
        name: "Product B2",
        description: "Description for Product B2",
        img: placeholderimg,
        cost: 155,
        subcategory: "Fantasy",
        subcategoryId: 7,
        stock: 40,
        Rating: 2,
      },
      {
        id: 205,
        name: "Product B5",
        description: "Description for Product B5",
        img: placeholderimg,
        cost: 120,
        subcategory: "Romance",
        subcategoryId: 9,
        stock: 45,
        Rating: 2,
      },
      {
        id: 208,
        name: "Product B8",
        description: "Description for Product B8",
        img: placeholderimg,
        cost: 95,
        subcategory: "Fantasy",
        subcategoryId: 7,
        stock: 48,
        Rating: 2,
      },
    ],
  },
  {
    id: 2,
    name: "Company B",
    categoryName: "Travel And Luggage",
    categoryId: 20,
    products: [
      {
        id: 203,
        name: "Product B3",
        description: "Description for Product B3",
        img: placeholderimg,
        cost: 130.22,
        subcategory: "Suitcases",
        subcategoryId: 8,
        stock: 35,
        Rating: 2,
      },
      {
        id: 206,
        name: "Product B6",
        description: "Description for Product B6",
        img: placeholderimg,
        cost: 100,
        subcategory: "Backpacks",
        subcategoryId: 10,
        stock: 55,
        Rating: 4,
      },
      {
        id: 209,
        name: "Product B9",
        description: "Description for Product B9",
        img: placeholderimg,
        cost: 110,
        subcategory: "Suitacses",
        subcategoryId: 8,
        stock: 38,
        Rating: 2,
      },
    ],
  },
  {
    id: 2,
    name: "Company B",
    categoryId: 1,
    categoryName: "Electronics",
    products: [
      {
        id: 201,
        name: "Product B1",
        description: "Description for Product B1",
        img: placeholderimg,
        cost: 45.56,
        subcategory: "Phones",
        subcategoryId: 3,
        stock: 50,
        Rating: 2,
      },
      {
        id: 204,
        name: "Product B4",
        description: "Description for Product B4",
        img: placeholderimg,
        cost: 80,
        subcategory: "Laptops",
        subcategoryId: 4,
        stock: 60,
        Rating: 2,
      },
      {
        id: 207,
        name: "Product B7",
        description: "Description for Product B7",
        img: placeholderimg,
        cost: 70,
        subcategory: "Laptops",
        subcategoryId: 4,
        stock: 70,
        Rating: 3,
      },
      {
        id: 210,
        name: "Product B10",
        description: "Description for Product B10",
        img: placeholderimg,
        cost: 150,
        subcategory: "Phones",
        subcategoryId: 3,
        stock: 65,
        Rating: 2,
      },
    ],
  },
  {
    id: 3,
    name: "Company C",
    categoryName: "Books",
    categoryId: 5,
    products: [
      {
        id: 302,
        name: "Product C2",
        description: "Description for Product C2",
        img: placeholderimg,
        cost: 55,
        subcategory: "Fantasy",
        subcategoryId: 7,
        stock: 20,
        Rating: 0,
      },
      {
        id: 305,
        name: "Product C5",
        description: "Description for Product C5",
        img: placeholderimg,
        cost: 90,
        subcategory: "Fantasy",
        subcategoryId: 7,
        stock: 22,
        Rating: 4,
      },
      {
        id: 308,
        name: "Product C8",
        description: "Description for Product C8",
        img: placeholderimg,
        cost: 120,
        subcategory: "Romance",
        subcategoryId: 9,
        stock: 28,
        Rating: 2,
      },
    ],
  },
  {
    id: 3,
    name: "Company C",
    categoryName: "Health And Beauty",
    categoryId: 3,
    products: [
      {
        id: 303,
        name: "Product C3",
        description: "Description for Product C3",
        img: placeholderimg,
        cost: 130,
        subcategory: "Skincare",
        subcategoryId: 12,
        stock: 15,
        Rating: 1,
      },
      {
        id: 306,
        name: "Product C6",
        description: "Description for Product C6",
        img: placeholderimg,
        cost: 105,
        subcategory: "Eye Makeup",
        subcategoryId: 14,
        stock: 18,
        Rating: 1,
      },
      {
        id: 309,
        name: "Product C9",
        description: "Description for Product C9",
        img: placeholderimg,
        cost: 95,
        subcategory: "Skincare",
        subcategoryId: 12,
        stock: 32,
        Rating: 2,
      },
    ],
  },
  {
    id: 3,
    name: "Company C",
    categoryName: "Accessories",
    categoryId: 6,
    products: [
      {
        id: 301,
        name: "Product C1",
        description: "Description for Product C1",
        img: placeholderimg,
        cost: 123,
        subcategory: "Bracelets",
        subcategoryId: 11,
        stock: 25,
        Rating: 2,
      },
      {
        id: 304,
        name: "Product C4",
        description: "Description for Product C4",
        img: placeholderimg,
        cost: 75,
        subcategory: "Necklaces",
        subcategoryId: 13,
        stock: 30,
        Rating: 3,
      },
      {
        id: 307,
        name: "Product C7",
        description: "Description for Product C7",
        img: placeholderimg,
        cost: 85,
        subcategory: "Bracelets",
        subcategoryId: 11,
        stock: 35,
        Rating: 3,
      },
      {
        id: 310,
        name: "Product C10",
        description: "Description for Product C10",
        img: placeholderimg,
        cost: 110,
        subcategory: "Necklaces",
        subcategoryId: 13,
        stock: 40,
        Rating: 2,
      },
    ],
  },
  {
    id: 4,
    name: "Company D",
    categoryName: "Accessories",
    categoryId: 6,
    products: [
      {
        id: 402,
        name: "Product D2",
        description: "Description for Product D2",
        img: placeholderimg,
        cost: 120,
        subcategory: "Necklaces",
        subcategoryId: 13,
        stock: 35,
        Rating: 2,
      },
      {
        id: 405,
        name: "Product D5",
        description: "Description for Product D5",
        img: placeholderimg,
        cost: 95,
        subcategory: "Rings",
        subcategoryId: 16,
        stock: 45,
        Rating: 2,
      },
      {
        id: 408,
        name: "Product D8",
        description: "Description for Product D8",
        img: placeholderimg,
        cost: 140,
        subcategory: "Rings",
        subcategoryId: 16,
        stock: 42,
        Rating: 2,
      },
    ],
  },
  {
    id : 4,
    name : "Company D",
    categoryName : "electronics", 
    categoryId : 1,
    products : [
        {
            id: 403,
            name: "Product D3",
            description:
              "longeeeeeeeeeeeeeeeeeeeeeeeeeeeeer Description for Product D3 bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
            img: placeholderimg,
            cost: 125,
            subcategory: "Laptops",
            subcategoryId: 4,
            stock: 30,
            Rating: 2,
        },
        {
          id: 406,
          name: "Product D6",
          description: "Description for Product D6",
          img: placeholderimg,
          cost: 130,
          subcategory: "Headphones",
          subcategoryId: 17,
          stock: 60,
          Rating: 2,
        },
        {
          id: 409,
          name: "Product D9",
          description: "Description for Product D9",
          img: placeholderimg,
          cost: 115,
          subcategory: "Laptops",
          subcategoryId: 4,
          stock: 38,
          Rating: 2,
        },
    ]
  }
  ,
  {
    id: 4,
    name: "Company D",
    categoryName: "Games",
    categoryId: 31,
    products: [
      {
        id: 401,
        name: "Product D1",
        description: "Description for Product D1",
        img: placeholderimg,
        cost: 120,
        subcategory: "Board Games",
        subcategoryId: 15,
        stock: 40,
        Rating: 2,
    },
      {
        id: 404,
        name: "Product D4",
        description: "Description for Product D4",
        img: placeholderimg,
        cost: 135,
        subcategory: "Board Games",
        subcategoryId: 15,
        stock: 50,
        Rating: 2,
      },
      {
        id: 407,
        name: "Product D7",
        description: "Description for Product D7",
        img: placeholderimg,
        cost: 110,
        subcategory: "Board Games",
        subcategoryId: 15,
        stock: 55,
        Rating: 2,
      },
      {
        id: 410,
        name: "Product D10",
        description: "Description for Product D10",
        img: placeholderimg,
        cost: 150,
        subcategory: "Board Games",
        subcategoryId: 15,
        stock: 48,
        Rating: 2,
      },
      {
        id: 411,
        name: "Product D11",
        description: "Description for Product D11",
        img: placeholderimg,
        cost: 150,
        subcategory: "Board Bames",
        subcategoryId: 15,
        stock: 48,
        Rating: 2,
      },
    ],
  },
];

export default companyCategoryData;
